[tool.poetry]
name = "kaggle-nfl"
version = "0.1.0"
description = ""
authors = ["19sergey98 <19sergey98@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.1.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
